// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8IHK4xrUlMwVIFnBFd9RuDh4s3AIlD4Y',
    appId: '1:809784257649:web:afc20104507ced061ebfd0',
    messagingSenderId: '809784257649',
    projectId: 'my-first-firebase-42152',
    authDomain: 'my-first-firebase-42152.firebaseapp.com',
    storageBucket: 'my-first-firebase-42152.appspot.com',
    measurementId: 'G-BWRPS60YJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfJdV23r0u5Gp0gbRDBRydIELnR04YHmw',
    appId: '1:809784257649:android:fb32a443f22dbce01ebfd0',
    messagingSenderId: '809784257649',
    projectId: 'my-first-firebase-42152',
    storageBucket: 'my-first-firebase-42152.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR3I268dusdJtBKsFaGqFwmyEN9rh16EQ',
    appId: '1:809784257649:ios:1929b2d6315aefc11ebfd0',
    messagingSenderId: '809784257649',
    projectId: 'my-first-firebase-42152',
    storageBucket: 'my-first-firebase-42152.appspot.com',
    iosClientId: '809784257649-q9074amc82s9jgs1m0uskin2os4c72je.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseproject',
  );
}
